export const variableIdentifierRegex = '([a-zA-Z][a-zA-Z_0-9]*)'
export const variablePropertyIdentifierRegex = '(\\.[a-zA-Z][a-zA-Z_0-9]*)'
export const variableTypeRegex = '[A-Z][a-zA-Z_0-9]*'
export const notRegex = '\\!'
export const whiteSpace = '\\s*'
export const assertionConditionEvent = '[a-zA-Z_0-9]+'